#!/usr/bin/env bash

set -Eeu
set -o pipefail
export PATH="/usr/sbin:$PATH"

CONF=(
  -f /srv/run/chrony/0-include.conf
  )


rm -fr -- /tmp/chronyd.pid
s6-envuidgid "$USER" chronyd -p "${CONF[@]}"
exec -- s6-envuidgid "$USER" chronyd "${CONF[@]}" -d -x -L 0
