#!/usr/bin/env bash

set -eu
set -o pipefail
export PATH="/usr/sbin:$PATH"


ARGS=(
  -d
  -x
  -f /srv/run/chrony/0-include.conf
  -L 0
  )


rm -rf -- /tmp/chronyd.pid
exec s6-envuidgid "$USER" chronyd "${ARGS[@]}"
