---
version: "3.9"

services:
  router:
    restart: always
    build: ./docker
    cap_add:
      - NET_ADMIN
    environment:
      - TZ
      - WAN_IF=eth0
      - LAN_IF=eth0
    network_mode: host
    volumes:
      - ./tmp:/data

