---
version: "3.8"

services:
  router:
    build: ./docker
    cap_add:
      - NET_ADMIN
    environment:
      - TZ
    devices:
      - /dev/ptp0
    network_mode: host
    volumes:
      - /data
      - ./config:/config:ro
