#!/usr/bin/env bash

set -Eeu
set -o pipefail
export PATH="/usr/sbin:$PATH"


ARGS=(
  --conf-dir /srv/run/dnsmasq/dhcp/conf.d
  )


s6-svwait -U /run/s6/legacy-services/unbound
exec s6-envuidgid "$USER" dnsmasq "${ARGS[@]}"
