#!/usr/bin/env bash

set -eu
set -o pipefail


CONF='/srv/run/unbound/0-include.conf'
ARGS=(
  -c "$CONF"
  )


rm --force -- '/tmp/unbound.sock'
unbound-checkconf -- "$CONF"
exec unbound "${ARGS[@]}"
