#!/usr/bin/env bash

set -eu
set -o pipefail


CONF='/srv/run/unbound/0-include.conf'
ARGS=(
  -c "$CONF"
  )


s6-setuidgid "$USER" unbound-checkconf -- "$CONF"
exec s6-notifyoncheck s6-envuidgid "$USER" unbound "${ARGS[@]}"
