#!/usr/bin/env bash

set -eu
set -o pipefail


ARGS=(
  -f /srv/run/squid/0-main.conf
  --foreground
  -d 1
  )


s6-setuidgid "$USER" squid "${ARGS[@]}" -z
exec s6-setuidgid "$USER" squid "${ARGS[@]}"

