#!/usr/bin/env bash

set -Eeu
set -o pipefail
export PATH="/usr/sbin:$PATH"


ARGS=(
  -f /srv/run/squid/0-main.conf
  --foreground
  -d 1
  )


rm -rf -- /tmp/squid.pid /tmp/squid
s6-setuidgid "$USER" squid "${ARGS[@]}" -z
exec -- s6-setuidgid "$USER" squid "${ARGS[@]}"

