#!/usr/bin/env bash

set -eu
set -o pipefail


ARGS=(
  -f /srv/run/squid/0-main.conf
  --foreground
  -d 1
  )


rm -rf -- /tmp/squid.pid /tmp/squid
s6-setuidgid "$USER" squid "${ARGS[@]}" -z
s6-setuidgid "$USER" /usr/lib/squid/security_file_certgen -c -s /tmp/squid_ssl_db -M 4MB
exec s6-setuidgid "$USER" squid "${ARGS[@]}"

