#!/usr/bin/env bash

set -eu
set -o pipefail


UNBOUND_ARGS=(
  -c /srv/run/unbound/lan/1-main.conf
  status
  )

ARGS=(
  --conf-dir /srv/run/dnsmasq/conf.d
  )


unbound-control "${UNBOUND_ARGS[@]}"
exec dnsmasq "${ARGS[@]}"
