#!/usr/bin/env bash

set -eu
set -o pipefail


ARGS=(
  --conf-dir /srv/run/dnsmasq/conf.d
  )


s6-setuidgid "$USER" /srv/run/unbound/ctl.sh status

exec 3<> "$(mkstemp)"
printf '%s' "rdy" >&3
exec 3>&-

exec dnsmasq "${ARGS[@]}"
