#!/usr/bin/env bash

set -eu
set -o pipefail
export PATH="/usr/sbin:$PATH"


ARGS=(
  --no-chroot
  --file /srv/run/avahi/0-main.conf
  )


rm -rf -- /var/run/avahi-daemon
exec s6-envuidgid "$USER" avahi-daemon "${ARGS[@]}"
