#!/usr/bin/env bash

set -Eeu
set -o pipefail
export PATH="/usr/sbin:$PATH"


ARGS=(
  /srv/run/ntop/0-main.conf
  )


mkdir -p -- /tmp/ntop
s6-svwait -U /run/s6/legacy-services/redis
s6-setuidgid "$USER" redis-cli -s /tmp/redis.sock flushall
exec -- ntopng "${ARGS[@]}"

