---
version: "3.8"

services:
  router:
    restart: always
    image: msjpq/router:latest
    cap_add:
      - NET_ADMIN
    environment:
      - TZ
      - WAN_IF=# Required <WAN interface name>
      - LAN_IF=# Required <LAN interface name>
    network_mode: host
    volumes:
      - ./:/config
      - ../../volumes/router:/data

