---
version: "3.8"

services:
  router:
    restart: always
    image: msjpq/router:latest
    cap_add:
      - NET_ADMIN
    environment:
      - TZ
      ## Required
      - WAN_IF=# <WAN interface name>
      - LAN_IF=# <LAN interface name>

      ## Recommended
      - GUEST_IF=# <Guest interface name>
      - DNS_SERVERS=# Set this to a pihole or something
      - WG_DOMAIN=# Server name / IP from WAN side, used for VPN clients
    network_mode: host
    volumes:
      - data:/data

      # Optional
      - ./nftables:/config/nftables # Your own firewall rules, if any
      # Optional
      - ./port_fwd:/config/port_fwd # Your own port forward rules, if any

volumes:
  # This stores DHCP leases and Wireguard keys
  data: {}
