---
version: "3.8"

services:
  router:
    restart: always
    image: msjpq/router:latest
    cap_add:
      - NET_ADMIN
    environment:
      - TZ
    network_mode: host
    volumes:
      - /data
      - ./config:/config:ro
