---
interfaces:
  wan:
  trusted:
  wireguard: wg0
  guest: null
  unmanaged:
    - "docker*"
  wan_pd_only: False

ip_addresses:
  ipv4:
    loopback_exclusions:
      - 127.0.0.0/16
    managed_network_exclusions:
      - 10.0.0.0/20
      - 192.168.0.0/20
      - 172.16.0.0/12
    managed_prefix_len: 24
    tor_prefix_len: 16
  ipv6:
    ula_global_prefix: null
    prefix_delegation: False

dhcp:
  lease_time: 1

dns:
  local_domains:
    trusted: t.home.arpa
    wireguard: w.home.arpa
    guest: g.home.arpa
  local_ttl: 1
  upstream_servers: []
  split_horizon:
    trusted: {}
    wireguard: {}
    guest: {}
  records:
    local.host:
      - 127.0.0.1
      - ::1
    localho.st:
      - 127.0.0.1
      - ::1
  private_domains: []

wireguard:
  server_name: ""
  peers: []

traffic_control:
  transmit:
    - diffserv4
    - wash
    - rtt
    - 50ms
  receive:
    - besteffort
    - wash
    - rtt
    - 10ms

port_bindings:
  wireguard: 51820
  squid: 3128
  tor: 1080
  statistics: 8080

port_forwards:
  trusted: {}
  wireguard: {}
  guest: {}

guest_accessible:
  trusted: {}
  wireguard: {}

ntp:
  enabled: True

  local_options: >-
    stratum 3

  refclock_options: >-
    stratum 3
