#!/usr/bin/env bash

set -eu
set -o pipefail
export PATH="/usr/sbin:$PATH"


s6-svwait -U /run/s6/legacy-services/unbound

while true
do
  /etc/services.d/unbound/data/check &>>/dev/null
  sleep 1
done
