---
name: Release

on:
  push:
    branches:
      - whale
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install -U -r requirements.txt -- mypy types-PyYAML

      - name: Lint
        run: mypy -- .

      - name: QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/router:latest
          context: ./docker
          platforms: linux/amd64,linux/arm64
